// Mappatura stazioni Italo: nome normalizzato -> codice stazione Italo.
// Codici verificati dall'API ufficiale api-biglietti.italotreno.com/api/v1/stations
// (campo stationCode) integrati con la wiki SimoDax/Italo-API.

export const ITALO_CODICI = {
  agropoli: 'AGR',
  aversa: 'AVR',
  bari: 'BAC',
  baricentrale: 'BAC',
  barletta: 'BLT',
  benevento: 'BEN',
  bisceglie: 'BIG',
  bologna: 'BC_',
  bolognacentrale: 'BC_',
  bolzano: 'BLZ',
  brescia: 'BSC',
  caserta: 'CEA',
  conegliano: 'CON',
  desenzano: 'DSG',
  desenzanodelgarda: 'DSG',
  desenzanodelgardasirmione: 'DSG',
  ferrara: 'F__',
  firenze: 'SMN',
  firenzecampodimarte: 'FCM',
  firenzerifredi: 'RIF',
  firenzesantamarianovella: 'SMN',
  firenzesmnovella: 'SMN',
  firenzesmn: 'SMN',
  foggia: 'FG_',
  genova: 'G__',
  genovapiazzaprincipe: 'G__',
  genovabrignole: 'GB_',
  lameziaterme: 'LON',
  lameziatermecentrale: 'LON',
  latisana: 'LTL',
  maratea: 'MRT',
  messina: 'MEN',
  milano: 'MC_',
  milanocentrale: 'MC_',
  napoli: 'NAC',
  napolicentrale: 'NAC',
  napoliafragola: 'NAF',
  padova: 'PD_',
  paola: 'PAO',
  pescara: 'PSC',
  pescaracentrale: 'PSC',
  reggioemilia: 'AAV',
  reggioemiliaav: 'AAV',
  mediopadana: 'AAV',
  mediopadanareemilia: 'AAV',
  reggiocalabria: 'RCC',
  reggiocalabriacentrale: 'RCC',
  roma: 'RMT',
  romatermini: 'RMT',
  romatiburtina: 'RTB',
  rovereto: 'RVR',
  salerno: 'SAL',
  sapri: 'SAP',
  taranto: 'TAR',
  torino: 'TOP',
  torinoportanuova: 'TOP',
  torinoportasusa: 'OUE',
  trani: 'TR_',
  trento: 'TCN',
  treviso: 'TVC',
  trevisocentrale: 'TVC',
  trieste: 'TSC',
  triestecentrale: 'TSC',
  udine: 'UD_',
  venezia: 'VEM',
  veneziamestre: 'VEM',
  veneziasantalucia: 'VSL',
  veneziaslucia: 'VSL',
  verona: 'VPN',
  veronaportanuova: 'VPN',
  vicenza: 'VIC',
  villasangiovanni: 'VLG',
}

// codice -> nome leggibile (per la visualizzazione)
export const ITALO_NOMI = {
  AGR: 'Agropoli', AVR: 'Aversa', BAC: 'Bari Centrale', BLT: 'Barletta',
  BEN: 'Benevento', BIG: 'Bisceglie', BC_: 'Bologna Centrale', BLZ: 'Bolzano',
  BSC: 'Brescia', CEA: 'Caserta', CON: 'Conegliano', DSG: 'Desenzano',
  F__: 'Ferrara', FCM: 'Firenze Campo di Marte', RIF: 'Firenze Rifredi',
  SMN: 'Firenze S. M. Novella', FG_: 'Foggia', G__: 'Genova Piazza Principe',
  GB_: 'Genova Brignole', LON: 'Lamezia Terme Centrale', LTL: 'Latisana-Lignano-Bibione',
  MRT: 'Maratea', MEN: 'Messina', MC_: 'Milano Centrale', NAF: 'Napoli Afragola',
  NAC: 'Napoli Centrale', PD_: 'Padova', PAO: 'Paola', PSC: 'Pescara Centrale',
  AAV: 'Mediopadana R. Emilia', RCC: 'Reggio Calabria Centrale', RMT: 'Roma Termini',
  RTB: 'Roma Tiburtina', RVR: 'Rovereto', SAL: 'Salerno', SAP: 'Sapri',
  TAR: 'Taranto', TOP: 'Torino Porta Nuova', OUE: 'Torino Porta Susa', TR_: 'Trani',
  TCN: 'Trento', TVC: 'Treviso Centrale', TSC: 'Trieste Centrale', UD_: 'Udine',
  VEM: 'Venezia Mestre', VSL: 'Venezia Santa Lucia', VPN: 'Verona Porta Nuova',
  VIC: 'Vicenza', VLG: 'Villa San Giovanni',
}

export function codiceItalo(nome) {
  const n = String(nome || '').toLowerCase().replace(/[^a-z0-9]/g, '')
  if (ITALO_CODICI[n]) return ITALO_CODICI[n]
  for (const k of Object.keys(ITALO_CODICI)) {
    if (k.length >= 6 && (n === k || n.startsWith(k) || k.startsWith(n))) return ITALO_CODICI[k]
  }
  return null
}
