// Mappatura stazioni servite da Italo: nome normalizzato -> codice Italo (3 char).
// Fonte: italoinviaggio.italotreno.com (array "Validazione stazione") + wiki SimoDax/Italo-API.
// Usata per tradurre la stazione scelta (nome LeFrecce) nel codice Italo del tabellone.

export const ITALO_CODICI = {
  agropoli: 'AGR',
  ancona: 'FF_',
  bari: 'BAC',
  baricentrale: 'BAC',
  barletta: 'BLT',
  benevento: 'BEN',
  bergamo: 'BGM',
  bisceglie: 'BIG',
  bologna: 'BC_',
  bolognacentrale: 'BC_',
  bolzano: 'BLZ',
  brescia: 'BSC',
  caserta: 'CEA',
  conegliano: 'CON',
  desenzano: 'DSG',
  desenzanodelgarda: 'DSG',
  desenzanodelgardasirmione: 'DSG',
  ferrara: 'F__',
  firenze: 'SMN',
  firenzesantamarianovella: 'SMN',
  firenzesmnovella: 'SMN',
  firenzesmn: 'SMN',
  foggia: 'FG_',
  genova: 'G__',
  genovapiazzaprincipe: 'G__',
  genovabrignole: 'GB_',
  lameziaterme: 'LON',
  lameziatermecentrale: 'LON',
  latisana: 'LTL',
  maratea: 'MRT',
  milano: 'MI0',           // Milano tutte le stazioni
  milanocentrale: 'MC_',
  milanorhofiera: 'RRO',
  rhofieramilano: 'RRO',
  milanorogoredo: 'RG_',
  napoli: 'NAC',
  napolicentrale: 'NAC',
  padova: 'PD_',
  paola: 'PAO',
  pesaro: 'PES',
  pescara: 'PSC',
  pescaracentrale: 'PSC',
  reggioemilia: 'AAV',
  reggioemiliaav: 'AAV',
  reggiocalabria: 'RCC',
  reggiocalabriacentrale: 'RCC',
  rimini: 'RMN',
  roma: 'RM0',             // Roma tutte le stazioni
  romatermini: 'RMT',
  romatiburtina: 'RTB',
  rovereto: 'ROV',
  salerno: 'SAL',
  sapri: 'SAP',
  taranto: 'TAR',
  torino: 'TOP',
  torinoportanuova: 'TOP',
  torinoportasusa: 'OUE',
  trento: 'TRT',
  trieste: 'TS_',
  triestecentrale: 'TS_',
  udine: 'UD_',
  venezia: 'VEM',
  veneziamestre: 'VEM',
  veneziasantalucia: 'VSL',
  veneziaslucia: 'VSL',
  verona: 'VPN',
  veronaportanuova: 'VPN',
  vicenza: 'VIC',
  villasangiovanni: 'VLG',
}

// urlCoding per costruire l'eventuale NomeStazione richiesto dal servizio
export const ITALO_NOMI = {
  VPN: 'Verona Porta Nuova',
  MC_: 'Milano Centrale',
  MI0: 'Milano (Tutte le stazioni)',
  RRO: 'Rho-Fiera Milano',
  RG_: 'Milano Rogoredo',
  BC_: 'Bologna Centrale',
  SMN: 'Firenze S. M. Novella',
  RMT: 'Roma Termini',
  RTB: 'Roma Tiburtina',
  RM0: 'Roma (Tutte le stazioni)',
  NAC: 'Napoli Centrale',
  PD_: 'Padova',
  VEM: 'Venezia Mestre',
  VSL: 'Venezia S. Lucia',
  BSC: 'Brescia',
  DSG: 'Desenzano',
  AAV: 'Reggio Emilia AV',
  TOP: 'Torino Porta Nuova',
  OUE: 'Torino Porta Susa',
  F__: 'Ferrara',
  G__: 'Genova Piazza Principe',
  GB_: 'Genova Brignole',
  SAL: 'Salerno',
  BAC: 'Bari Centrale',
  FF_: 'Ancona',
  PSC: 'Pescara Centrale',
  LON: 'Lamezia Terme Centrale',
  RCC: 'Reggio Calabria Centrale',
  TS_: 'Trieste Centrale',
  UD_: 'Udine',
  BGM: 'Bergamo',
  BLZ: 'Bolzano',
  TRT: 'Trento',
  ROV: 'Rovereto',
  VIC: 'Vicenza',
  CON: 'Conegliano',
}

export function codiceItalo(nome) {
  const n = String(nome || '').toLowerCase().replace(/[^a-z0-9]/g, '')
  if (ITALO_CODICI[n]) return ITALO_CODICI[n]
  // tolleranza: prova a matchare per inclusione (es. "veronaportanuovavr")
  for (const k of Object.keys(ITALO_CODICI)) {
    if (k.length >= 6 && (n === k || n.startsWith(k) || k.startsWith(n))) return ITALO_CODICI[k]
  }
  return null
}
